"""Reproducible Task 1 enrichment records."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.data_loader import REQUIRED_COLUMNS, load_unified_data

COLLECTED_BY = "Mariamawit_Alemu"
COLLECTION_DATE = "2026-07-19"

ENRICHMENT_RECORDS = [
    {
        "record_id": "REC_0034",
        "parent_id": "",
        "record_type": "observation",
        "category": "",
        "pillar": "ACCESS",
        "indicator": "Account Ownership Rate",
        "indicator_code": "ACC_OWNERSHIP",
        "indicator_direction": "higher_better",
        "value_numeric": 14,
        "value_text": "",
        "value_type": "percentage",
        "unit": "%",
        "observation_date": "2011-12-31",
        "period_start": "",
        "period_end": "",
        "fiscal_year": "2011",
        "gender": "all",
        "location": "national",
        "region": "",
        "source_name": "Global Findex 2011",
        "source_type": "survey",
        "source_url": "https://www.worldbank.org/en/publication/globalfindex",
        "confidence": "high",
        "related_indicator": "",
        "relationship_type": "",
        "impact_direction": "",
        "impact_magnitude": "",
        "impact_estimate": "",
        "lag_months": "",
        "evidence_basis": "",
        "comparable_country": "",
        "collected_by": COLLECTED_BY,
        "collection_date": COLLECTION_DATE,
        "original_text": "Ethiopia account ownership in 2011: 14%.",
        "notes": "Completes the 2011-2024 Global Findex access trajectory required for Task 2.",
    },
    {
        "record_id": "REC_0035",
        "parent_id": "",
        "record_type": "observation",
        "category": "",
        "pillar": "USAGE",
        "indicator": "Made or Received a Digital Payment",
        "indicator_code": "USG_DIGITAL_PAYMENT",
        "indicator_direction": "higher_better",
        "value_numeric": 35,
        "value_text": "approximately 35",
        "value_type": "percentage",
        "unit": "%",
        "observation_date": "2024-11-30",
        "period_start": "",
        "period_end": "",
        "fiscal_year": "2024",
        "gender": "all",
        "location": "national",
        "region": "",
        "source_name": "Global Findex 2024",
        "source_type": "survey",
        "source_url": "https://www.worldbank.org/en/publication/globalfindex",
        "confidence": "medium",
        "related_indicator": "",
        "relationship_type": "",
        "impact_direction": "",
        "impact_magnitude": "",
        "impact_estimate": "",
        "lag_months": "",
        "evidence_basis": "",
        "comparable_country": "",
        "collected_by": COLLECTED_BY,
        "collection_date": COLLECTION_DATE,
        "original_text": "Made or received a digital payment: approximately 35% in 2024.",
        "notes": "Adds the core Findex usage outcome requested for the forecasting system.",
    },
    {
        "record_id": "REC_0036",
        "parent_id": "",
        "record_type": "observation",
        "category": "",
        "pillar": "USAGE",
        "indicator": "Used Account to Receive Wages",
        "indicator_code": "USG_WAGES_ACCOUNT",
        "indicator_direction": "higher_better",
        "value_numeric": 15,
        "value_text": "approximately 15",
        "value_type": "percentage",
        "unit": "%",
        "observation_date": "2024-11-30",
        "period_start": "",
        "period_end": "",
        "fiscal_year": "2024",
        "gender": "all",
        "location": "national",
        "region": "",
        "source_name": "Global Findex 2024",
        "source_type": "survey",
        "source_url": "https://www.worldbank.org/en/publication/globalfindex",
        "confidence": "medium",
        "related_indicator": "",
        "relationship_type": "",
        "impact_direction": "",
        "impact_magnitude": "",
        "impact_estimate": "",
        "lag_months": "",
        "evidence_basis": "",
        "comparable_country": "",
        "collected_by": COLLECTED_BY,
        "collection_date": COLLECTION_DATE,
        "original_text": "Used an account to receive wages: approximately 15% in 2024.",
        "notes": "Adds a concrete payment use case and helps separate account access from meaningful usage.",
    },
    {
        "record_id": "REC_0037",
        "parent_id": "",
        "record_type": "observation",
        "category": "",
        "pillar": "ACCESS",
        "indicator": "Registered Mobile Money Accounts",
        "indicator_code": "ACC_MM_REGISTERED",
        "indicator_direction": "higher_better",
        "value_numeric": 128500000,
        "value_text": "more than 128.5 million",
        "value_type": "count",
        "unit": "accounts",
        "observation_date": "2024-12-31",
        "period_start": "",
        "period_end": "",
        "fiscal_year": "2024",
        "gender": "all",
        "location": "national",
        "region": "",
        "source_name": "National Bank of Ethiopia",
        "source_type": "regulator",
        "source_url": "https://nbe.gov.et/nbe_news/ethiopia-launches-phase-two-of-national-digital-payments-strategy-building-on-strong-momentum-from-phase-one/",
        "confidence": "high",
        "related_indicator": "",
        "relationship_type": "",
        "impact_direction": "",
        "impact_magnitude": "",
        "impact_estimate": "",
        "lag_months": "",
        "evidence_basis": "",
        "comparable_country": "",
        "collected_by": COLLECTED_BY,
        "collection_date": COLLECTION_DATE,
        "original_text": "Mobile money accounts exceeded 128.5 million by December 31, 2024.",
        "notes": "Supply-side registration volume helps investigate why account counts can rise faster than unique-adult inclusion.",
    },
    {
        "record_id": "REC_0038",
        "parent_id": "",
        "record_type": "observation",
        "category": "",
        "pillar": "USAGE",
        "indicator": "Active Mobile Money Account Share",
        "indicator_code": "USG_MM_ACTIVE_SHARE",
        "indicator_direction": "higher_better",
        "value_numeric": 15,
        "value_text": "only 15% active",
        "value_type": "percentage",
        "unit": "% of accounts",
        "observation_date": "2025-12-09",
        "period_start": "",
        "period_end": "",
        "fiscal_year": "2025",
        "gender": "all",
        "location": "national",
        "region": "",
        "source_name": "NBE Draft National Digital Payments Strategy 2026-2030",
        "source_type": "policy",
        "source_url": "https://nbe.gov.et/ndps/",
        "confidence": "medium",
        "related_indicator": "",
        "relationship_type": "",
        "impact_direction": "",
        "impact_magnitude": "",
        "impact_estimate": "",
        "lag_months": "",
        "evidence_basis": "",
        "comparable_country": "",
        "collected_by": COLLECTED_BY,
        "collection_date": COLLECTION_DATE,
        "original_text": "Only 15% of accounts and 25% of agents are active.",
        "notes": "System-wide activity estimate supports registered-versus-active analysis; definitions differ from provider 90-day activity.",
    },
    {
        "record_id": "EVT_0011",
        "parent_id": "",
        "record_type": "event",
        "category": "policy",
        "pillar": "",
        "indicator": "National Digital Payments Strategy Phase Two Launch",
        "indicator_code": "EVT_NDPS2",
        "indicator_direction": "",
        "value_numeric": "",
        "value_text": "Launched",
        "value_type": "categorical",
        "unit": "",
        "observation_date": "2025-03-28",
        "period_start": "",
        "period_end": "",
        "fiscal_year": "2025",
        "gender": "all",
        "location": "national",
        "region": "",
        "source_name": "National Bank of Ethiopia",
        "source_type": "policy",
        "source_url": "https://nbe.gov.et/nbe_news/ethiopia-launches-phase-two-of-national-digital-payments-strategy-building-on-strong-momentum-from-phase-one/",
        "confidence": "high",
        "related_indicator": "",
        "relationship_type": "",
        "impact_direction": "",
        "impact_magnitude": "",
        "impact_estimate": "",
        "lag_months": "",
        "evidence_basis": "",
        "comparable_country": "",
        "collected_by": COLLECTED_BY,
        "collection_date": COLLECTION_DATE,
        "original_text": "The National Bank of Ethiopia announced Phase Two on March 28, 2025.",
        "notes": "A major policy intervention focused on interoperability, usage, digital ID integration, and merchant acceptance.",
    },
    {
        "record_id": "IMP_0015",
        "parent_id": "EVT_0011",
        "record_type": "impact_link",
        "category": "",
        "pillar": "USAGE",
        "indicator": "NDPS Phase Two effect on Digital Payment Adoption",
        "indicator_code": "",
        "indicator_direction": "",
        "value_numeric": 10,
        "value_text": "",
        "value_type": "percentage",
        "unit": "%",
        "observation_date": "2025-03-28",
        "period_start": "",
        "period_end": "",
        "fiscal_year": "2025",
        "gender": "all",
        "location": "national",
        "region": "",
        "source_name": "National Bank of Ethiopia",
        "source_type": "policy",
        "source_url": "https://nbe.gov.et/nbe_news/ethiopia-launches-phase-two-of-national-digital-payments-strategy-building-on-strong-momentum-from-phase-one/",
        "confidence": "medium",
        "related_indicator": "USG_DIGITAL_PAYMENT",
        "relationship_type": "enabling",
        "impact_direction": "increase",
        "impact_magnitude": "medium",
        "impact_estimate": 10,
        "lag_months": 12,
        "evidence_basis": "expert",
        "comparable_country": "",
        "collected_by": COLLECTED_BY,
        "collection_date": COLLECTION_DATE,
        "original_text": "Phase Two focuses on deepening digital-payment usage and merchant acceptance.",
        "notes": "Modeling assumption, not an observed causal estimate; test during Task 3 sensitivity analysis.",
    },
    {
        "record_id": "IMP_0016",
        "parent_id": "EVT_0011",
        "record_type": "impact_link",
        "category": "",
        "pillar": "ACCESS",
        "indicator": "NDPS Phase Two effect on Account Ownership",
        "indicator_code": "",
        "indicator_direction": "",
        "value_numeric": 5,
        "value_text": "",
        "value_type": "percentage",
        "unit": "%",
        "observation_date": "2025-03-28",
        "period_start": "",
        "period_end": "",
        "fiscal_year": "2025",
        "gender": "all",
        "location": "national",
        "region": "",
        "source_name": "National Bank of Ethiopia",
        "source_type": "policy",
        "source_url": "https://nbe.gov.et/nbe_news/ethiopia-launches-phase-two-of-national-digital-payments-strategy-building-on-strong-momentum-from-phase-one/",
        "confidence": "medium",
        "related_indicator": "ACC_OWNERSHIP",
        "relationship_type": "enabling",
        "impact_direction": "increase",
        "impact_magnitude": "medium",
        "impact_estimate": 5,
        "lag_months": 18,
        "evidence_basis": "expert",
        "comparable_country": "",
        "collected_by": COLLECTED_BY,
        "collection_date": COLLECTION_DATE,
        "original_text": "Phase Two aims to expand inclusive digital financial services nationwide.",
        "notes": "Conservative modeling assumption with a longer lag because policy-to-ownership effects require onboarding and trust.",
    },
]


def enrichment_frame() -> pd.DataFrame:
    """Return additions in exact unified-schema column order."""
    return pd.DataFrame(ENRICHMENT_RECORDS, columns=REQUIRED_COLUMNS)


def build_enriched_dataset(raw_path: str | Path, output_path: str | Path) -> pd.DataFrame:
    """Append documented additions, reject duplicate IDs, and save the result."""
    raw = load_unified_data(raw_path)
    additions = enrichment_frame()
    overlap = set(raw["record_id"].dropna()) & set(additions["record_id"])
    if overlap:
        raise ValueError(f"Enrichment record IDs already exist: {sorted(overlap)}")

    # Convert raw date columns back to ISO strings before writing a portable CSV.
    raw_out = raw.copy()
    for column in ["observation_date", "period_start", "period_end", "collection_date"]:
        raw_out[column] = raw_out[column].dt.strftime("%Y-%m-%d").fillna("")

    enriched = pd.concat([raw_out, additions], ignore_index=True)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    enriched.to_csv(output_path, index=False)
    return enriched
